language: python
sudo: false
dist: trusty
python:
    - "3.5"
    - "3.6"
env:
    - DJANGO_VERSION=1.10.7
    - DJANGO_VERSION=1.11.3
install:
    - pip install -r requirements.txt
script:
    - python manage.py test
